### ISSUE TITLE
We should also be adding "distinct" pairs to training data

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#103]
![screenshot from 2015-02-26 10 48 38](https://cloud.githubusercontent.com/assets/536941/6396632/29e2f1b8-bda5-11e4-8e37-8005877f7696.png)

**Comment by evz** [comment]
I'll take a look at why this isn't happening. 

Oh, and this may be related to #105. Just noticed that the training data has 17,618 "match" pairs. That gets passed back and forth between the app and Redis every time you load a new pair while training. I'm not sure that would mean that it would take 10-15 minutes but it would certainly mean that it would take longer.

**Comment by fgregg** [comment]
Definitely don't need to be keeping that much training data. a few hundred
in each class should be sufficient.

**Comment by evz** [comment]
What's the best approach? Stop appending new data after a while? Or replace old training with new training? Or something else?

**Comment by fgregg** [comment]
Let's do FIFO.
