### ISSUE TITLE
Adding training data to 'contributions.csv' takes a long time.

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#105]
![screenshot from 2015-02-26 11 00 55](https://cloud.githubusercontent.com/assets/536941/6396890/d3fa201c-bda6-11e4-9577-d4c36b845e03.png)

**Comment by evz** [comment]
What's a long time? Does it just hang or does it eventually return?

**Comment by fgregg** [comment]
10-15 minutes, it does eventually return.

**Comment by evz** [comment]
Woah. OK. That's unusual. Looking into that this morning.

**Comment by fgregg** [comment]
FIFO should have fixed this.
