### ISSUE TITLE
zombie processes and matching

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#111]
I'm not sure why we are getting that error message and zombie processes in gazetteMatching.

However, we probably don't want multiprocessing for matching anyway. Let's just turn off multiprocessing for matching when we set up the StaticGazetteer class.

**Comment by fgregg** [comment]
actually, here's an idea of an actual cause

With the way we have written the matchBlocks call, it's possible to pass in an empty canonical_records, which wasn't possible when we did the index, match way. Let's check for that.

**Comment by fgregg** [comment]
Curiouser and curiouser:

According to Sentry, he exception actually starts on https://github.com/datamade/dedupe-api/blob/98d3ea933a2dc796546e2281bf8b0c0cb0f9aee2/api/utils/helpers.py#L270

Which, again according to sentry calls the staticgazetteer **match** method. I don't see how that's possible.

**Comment by evz** [comment]
Since updating to Python 3.4, I have not seen any zombies.

**Comment by fgregg** [comment]
WOOOT!
