### ISSUE TITLE
'go back' or 'undo' button for training 

### ISSUE THREAD

**Issue by derekeder** [datamade/dedupe-api#114]
There's no way to undo an incorrect labeling in the training step. This happens often.

**Comment by jernsthausen** [comment]
+1 on this. It'd be a huge improvement, since I think people can get kinda mind-numb at a point, especially, actually, in the later phases of the process.

**Comment by evz** [comment]
It seems like the approach we might take is to make a table where we store the training pairs along with information about when the decision was made and who made it. This will make it pretty simple to rewind a particular users most recent decisions as well as keep track of who made which decisions.

**Comment by derekeder** [comment]
:+1: for this approach

**Comment by evz** [comment]
This functionality was added in here: cbed6c992533d164cfff2521babdc887ec109501 There are still some UI quirks to work out with it but the basics are there.
