### ISSUE TITLE
Figure out a way to make review uncertainty measure a little friendlier

### ISSUE THREAD

**Issue by evz** [datamade/dedupe-api#119]
Right now if you cast doubt onto the review process by deciding that even one or two of the clusters are not actual clusters, the measure of how many records will end up in the wrong cluster takes quite a long time to come back down to a reasonable level so that one can bulk accept the rest of the queue. This doesn't entirely make sense since we are dynamically sorting the list by our measure of certainty that a record should be in the cluster on the fly (therefore presenting the records with low confidence first). Let's figure a way to make this better.

**Comment by fgregg** [comment]
The simple way to do this is to only use the most recent N examples (FIFO).
The more principled way to do this is to down weight older observations in
the logistic regression. I'll open up an issue to do add case-weighting to
rlr, but in the meantime, let's just do the forgetting.

**Comment by evz** [comment]
What's a good number to hold on to? 100? 1000?

**Comment by fgregg** [comment]
30.
