### ISSUE TITLE
match review progress measure

### ISSUE THREAD

**Issue by jernsthausen** [datamade/dedupe-api#120]
Presently, it is unclear to the user how many records require review in the final review stage. The number next to "left to review" seems to grow if you reject suggested possible clusters for unclustered records. It'd be very helpful to have some gauge of how many records remain to be reviewed.

**Comment by fgregg** [comment]
Working on this in #119

**Comment by fgregg** [comment]
@evz One thing that would help with this a lot is is to randomly shuffle the final review queue. Let's try that.

**Comment by fgregg** [comment]
(just shuffle once at the beginning)

**Comment by evz** [comment]
I'll just do an ``ORDER BY RANDOM`` when it goes to populate that review queue. 

@jernsthausen Just for a bit of context, that queue basically represents all of the records that are not yet present in the entity map. That means that, for datasets that are relatively canonical before starting (meaning there were not that many duplicates), there are going to be a bunch that end up needing to get run through this task. When it first starts this task, we run a query to get all of those records and then iterate the results attempting to match them to the records that we already have in the entity map. While doing this, if we find matches that we are not sure about, we pop them into a review queue that will need to be reviewed by a human. Then, as the human reviews the queue, we continue to do this same thing until we're out of records. As you can imagine, each time we iterate the remainder of records, we're automatically accepting or rejecting quite a few. So, this means for every 20 that end up needing human review, we might iterate 1000 or 2000. This makes predicting the number of records that will actually need to be reviewed by a human somewhat tricky and the reason why it seems somewhat erratic at first is directly related to that.

I think what we'll do is just round that number and not present it as an exact figure for now.

**Comment by jernsthausen** [comment]
@evz thanks for the breakdown. That helps my understanding of the number. I think it'll confuse people to not see it declining. If there's a way (and maybe this is for after some user data is collected) to estimate the time/records at the beginning of the process that one could expect to review, it would be helpful for folks in terms of determining "do I have time to knock this out now" or "should I get some other people to log onto this project and help out".

**Comment by fgregg** [comment]
Yeah. The shuffling will help us more quickly converge on an accurate
estimate. We can also hide the estimate until the standard error falls
below some threshold. (the estimate stops bouncing around)

**Comment by jernsthausen** [comment]
Sounds good. I think we'll get some good feedback once we have non-data-experts doing review.

**Comment by derekeder** [comment]
[Pushed up some changes](https://github.com/datamade/dedupe-api/commit/624c2e6f982f3de4611ea5fdede4effa833a550d) that hopefully will help with this. Here's my approach for now, though I'm sure it can be refined more.

* when the page first loads, show 'calculating ... (review more for an estimate)
* keep track of the previous iteration's estimate. if the number starts going down, display a number
* above 30 records, round to the nearest 10 (for example 'about 340')
* under 10, show a message of 'almost done'. I found that even at that point, you can have only 3, 2 or 1 records left for a bit.

Open to tweaks & suggestions.

**Comment by fgregg** [comment]
Those sound good. Eric and I found an important and subtle bug on how we
are calculating this under the hood.  Once we fix that, I may have some
ideas for UX.

Just to record the bug.

We should be calculating the fraction of items sent for human review over
the items reviewed by the machine PLUS items sent to human review. Instead
we have been calculating the ratio of items that have been reviewed by a
human to the number of items of reviewed by the machine. Eventually, that
later ratio should converge to the proportion that we want but it will take
a looooong time.

**Comment by derekeder** [comment]
Ok - I ended up getting even more confused after the changes described above, so I reverted them back but changed the label to 'Uncertain records'. 

I think returning the confidence in our number and displaying it as low|med|high would be a better approach.

**Comment by fgregg** [comment]
Let's wait on this until Eric and I sort out the bugs.

**Comment by fgregg** [comment]
Okay, @evz and have changed this code so that every stage, we are returning the upper bound of the a 95% confidence interval of the number of items that are left to review.

```
num_unreviewed_items * (estimated_human_review_proportion 
                        +  2 * estimated_human_review_proportion_standard_error)
```
```
As the review queue, this number will decrease for two reasons. The first reason is that the number of unreviewed items will decrease. The second is that the second term will converge, in expectation, to the true proportion of items to be reviewed.

Since, this number returned to the user will basically always decrease, I think we can do away with the "confidence" element in the UX.
