### ISSUE TITLE
For variable types like Text we can supply corpus to improve distance measure, are we using this?

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#122]
http://dedupe.readthedocs.org/en/latest/Variable-definition.html#text-types

**Comment by evz** [comment]
Nope. Not sure how we would do this. I guess we could take user input? Is there a way to find a corpus without that?

**Comment by fgregg** [comment]
https://github.com/datamade/dedupe-examples/blob/master/record_linkage_example/record_linkage_example.py#L112

**Comment by evz** [comment]
When does the corpus actually get used? I'm wondering if I need to actually store it with the variable definitions or if I can just quickly add it in advance of certain steps. I could see the performance taking a hit anytime we have to read it into memory and then write it back out to the database.

**Comment by fgregg** [comment]
Right now, it's pickled with the field definition. Let's see how it effects
performance.
