### ISSUE TITLE
First review seems to finish early

### ISSUE THREAD

**Issue by evz** [datamade/dedupe-api#131]
When one finishes the first review and triggers the work that is required to setup the second review ("merge entities") it seems as if the "processing" flag on the session is getting updated before the work actually finishes (or, for some reason, the work is being done twice, the second time without the processing flag getting toggled on). The consequences of this are that if you start merging entities before the processing is truly done, you observe #91 and the session can end up in a state that makes it unable to advance to the next stage.

**Comment by fgregg** [comment]
Does this also fix #91?

**Comment by evz** [comment]
Yes. It should.
