### ISSUE TITLE
If uploaded data has record_id column, things break

### ISSUE THREAD

**Issue by evz** [datamade/dedupe-api#132]
When uploading a dataset, if there is a column called ``record_id``, we can't bulk insert it since that is the name of the column we are adding to do all of our joins, etc, later on. 

The right way to solve this would be to allow a user to select a field that has something like a primary key in it (so, for instance if they've added an auto incrementing integer or something to a dataset) that will allow us to to keep the relationships and only if there isn't one present will we mint one. This will also help us allow for users to ensure that the data they upload can be linked back to their internal systems (without needing to have an extra crosswalk table or whatever)

For now, I think I'll just make sure that this kind of collision doesn't happen and work on implementing the right way later.

**Comment by fgregg** [comment]
Is this fixed?

**Comment by evz** [comment]
Yeah, guess I forgot to close
