### ISSUE TITLE
If a field has an 'Exists?' variable defined on it, then any other variables defined on the field as not missing

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#133]
"Exists?" explicitly checks if a field value exists, it won't work properly if there is another variable defined on the same field that has missing data handling turned on.

**Comment by evz** [comment]
OK, so if ``Exists``, force ``has missing`` to be false (or just not defined)?

**Comment by fgregg** [comment]
Yes, for all variables defined on that field.
