### ISSUE TITLE
Writing blocking map failed for Georgia Contributions on unicode error

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#137]
https://app.getsentry.com/datamade/dedupe-api-worker/group/58951469/

When trying to write the blocking map to CSV. The cause is that the default encoding on the server is not utf-8

```<_io.TextIOWrapper name='/tmp/585972b3-2f22-4830-9ed9-fb4dc26e0335.csv' mode='w' encoding='ANSI_X3.4-1968'>```

Seems to me that the right way to do this is to explicitly set the encoding we want for the file: 

```open('foo', 'w', encoding='utf-8')```

**Comment by evz** [comment]
Looks like this was fixed with 0a1dcf56813369d900368656657b7576253a44c9
