### ISSUE TITLE
UX, give indication that session has been moved from "In progress" to "canonical"

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#140]
I have gotten very confused by this. Relates to #136

**Comment by derekeder** [comment]
Yah I've been meaning to rewrite this since i split up the 'in progress' and 'canonical' tabs. Taking it on now.

**Comment by derekeder** [comment]
closed via a01d40098b51bd98ff2ef9fd7a1bd1a91d470c8b
