### ISSUE TITLE
Merge entities step skipped

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#143]
When moving Federal lobbyists through the paces, when I went to merge entities it said nothing to review. Hard to believe that is true.

**Comment by evz** [comment]
This is probably related to #131. When you finish the first review and starts getting the second review step together, it sometimes sets the ``processing`` flag on the session as ``FALSE`` too early (before it's actually done processing). I have yet to pin down where this is happening. Which sounds insane, I know, but it's been elusive so far.

**Comment by fgregg** [comment]
Is this also fixed, since #131 was fixed?

**Comment by evz** [comment]
Oh, yeah, for some reason I was reading this a little differently. If after the first review dedupe is unable to find any clusters of canonical forms of entities, it goes ahead and advances to the final review. Which I guess is reasonable. This, however, is not that.
