### ISSUE TITLE
Merge entities is not resetting final review step

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#145]
For CRP: http://dedupeapi.datamade.us/session-admin/?session_id=f798fda7-cc4e-43e7-b852-b9b90eb3bf37

**Comment by evz** [comment]
So, when you attempt to roll back this session, it doesn't do anything?

**Comment by fgregg** [comment]
Yup.

**Comment by evz** [comment]
So, part of this could be a UI nuance. Right now when you have a dataset under the "canonical" tab and then want to roll it back to a prior state, it stays in the canonical tab until the rollback is completed and the status gets updated.

**Comment by evz** [comment]
Related: https://github.com/datamade/dedupe-api/commit/7e5c2f9

**Comment by fgregg** [comment]
This seems to be working now.
