### ISSUE TITLE
Style guide for dedupe-api

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#149]
There are some big, big functions in this code, and a lot of boilerplate. As I'm working on this code I am tempted to refactor some things, but let's get on the same page as to a good style.

**Comment by evz** [comment]
@fgregg Thanks. This will help a lot.

**Comment by fgregg** [comment]
Where we landed:

- camelCase for functions with the first letter uncapitalized
- small functions are nice, let's do more of those. Put them at the bottom of the the file
- helpers is not the best name for a module, let's slowly move things out of there into more sensical namespaces.

Does that seem about right @evz

**Comment by fgregg** [comment]
New one 

- Namespaces are good idea. Prefer 

```python
import itertools
...
for i, j in itertools.combination(foo, 2) :
...
```

over

```python
from itertools import combination
...
for i, j in combination(foo, 2) :
...
```

Thoughts @evz?
