### ISSUE TITLE
Profile and optimize the matching.

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#162]
Because of all the improvements we've been making in #148 the fraction of records going to human review is getting smaller, and the time it takes to process a single records is getting longer. This means that the reviewer can wait a long time to get something to review. 

Let's profile and optimize this part of the code.

**Comment by fgregg** [comment]
@evz has been making progress on this. the call to matchBlocks is now taking 75% of the time. We only calling one record at a time, and we could speed this up by matching multiple records.

The best way to do this would be to subclass dedupe's Gazetteer class to make it DB aware. This shouldn't be too hard.

Gazetteer's match method https://github.com/datamade/dedupe/blob/master/dedupe/api.py#L1071

takes in a dictionary of messy records and does two things. It calls _blockData to make blocks
and then calls matchBlocks to .... match those blocks.

_blockData just calls _blockGenerator with the ```messy_data`` and ```blocked_records```

```blocked_records``` is a dictionary, where the keys are block keys and the values are dictionaries of (record_id, records).

for the DB aware, we'll pass in info to identify a block table in a database.

Then, we'll modify _blockGenerator https://github.com/datamade/dedupe/blob/master/dedupe/api.py#L441 to grab records from the table instead of from the dictionary.

@evz, make sense?

**Comment by evz** [comment]
OK, so when you say "``_blockData`` just calls ``_blockGenerator`` with the ``messy_data`` and ``blocked_records``" where are the ``blocked_records`` coming from? Or did you unintentionally repeat ``blocked_records`` there?

**Comment by fgregg** [comment]
https://github.com/datamade/dedupe/blob/master/dedupe/api.py#L1040

`self.blocked_records` is a previously build index of canonical records to match against.

**Comment by evz** [comment]
I'm going to go ahead and close this. With the introduction of the [``DatabaseGazetteer``](https://github.com/datamade/dedupe-api/blob/master/api/utils/helpers.py#L106) it seems like the bulk of the time (~95%) is spent inside the call to ``match`` and that time has been reduced quite a bit since we are matching a bunch of records at a time.
