### ISSUE TITLE
Don't store corpus in field definitions for Text and Set

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#164]
I don't think there's any benefit to storing the corpuses with the field definitions of Text and Set field defintions. These can be very big, and make it difficult to view the datamodel.

**Comment by evz** [comment]
This has been addressed by implementing a [``readFieldDefs``](https://github.com/datamade/dedupe-api/blob/master/api/utils/helpers.py#L194) function which pulls together the appropriate things on the fly.
