### ISSUE TITLE
Duplicate records while making entity map 

### ISSUE THREAD

**Issue by evz** [datamade/dedupe-api#167]
Somehow, we're occasionally ending up with duplicate record ids when calling [``initializeEntityMap``](https://github.com/datamade/dedupe-api/blob/master/api/utils/db_functions.py#L140). This gives us errors like this:

```
IntegrityError: duplicate key value violates unique constraint "ix_entity_585972b3-2f22-4830-9ed9-fb4dc26e0335_record_id"
DETAIL:  Key (record_id)=(262148) already exists.
CONTEXT:  COPY entity_585972b3-2f22-4830-9ed9-fb4dc26e0335, line 1
```

**Comment by fgregg** [comment]
Where are we on this?

**Comment by fgregg** [comment]
Could this have been fixed by https://github.com/datamade/dedupe-api/commit/ca4d9d02105caee4cca4274bac77b2e34e98e443
