### ISSUE TITLE
Can't get to review cluster stage on AJC 

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#169]
When I click on "review clusters" in the setting page, it spins, and finally lands on "merge entities".

**Comment by evz** [comment]
I'm not entirely sure what would have caused this other than not getting anything back from ``matchBlocks``. This is pretty unlikely given the dataset and the fact that it backs off the threshold from 0.75 (in increments of 0.1) until it gets to 0.1 and then, if it still has not gotten anything back from ``matchBlocks``, it advances to the next step. 

If the session was already in the "Merge Entities" step and you were attempting to roll it back, this could have been the result of an error happening at some point while attempting to roll it back. If the error happened before the session status got updated to "Review Entities", that could have been another reason.
