### ISSUE TITLE
Yet another integrity error, this time on match blocks:

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#170]
On CRP:
https://app.getsentry.com/datamade/dedupe-api-worker/group/60502043/

```
(IntegrityError) duplicate key value violates unique constraint "pg_class_relname_nsp_index" DETAIL: Key (relname, relnamespace)=(match_blocks_key_f798fda7-cc4e-43e7-b852-b9b90eb3bf37_idx, 2200) already exists. '\n CREATE INDEX "match_blocks_key_f798fda7-cc4e-43e7-b852-b9b90eb3bf37_idx" \n ON "match_blocks_f798fda7-cc4e-43e7-b852-b9b90eb3bf37" (block_key)\n ' {}
```

**Comment by fgregg** [comment]
This seems to be complaining that we are trying to create an index that has already been created.

**Comment by evz** [comment]
Weird thing is that it gets dropped right before that: https://github.com/datamade/dedupe-api/blob/master/api/utils/delayed_tasks.py#L216-L222

**Comment by fgregg** [comment]
Do we have multiple workers trying to do the same thing?

**Comment by fgregg** [comment]
Where are we on this?

**Comment by fgregg** [comment]
Could this have been fixed by https://github.com/datamade/dedupe-api/commit/ca4d9d02105caee4cca4274bac77b2e34e98e443

**Comment by evz** [comment]
There's a distinct possibility. That was the main motivation for doing all of that stuff in memory instead of writing to disk.
