### ISSUE TITLE
Don't learn negative examples from rejection of large cluster

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#176]
Only learn negative examples where its' unambiguous that all the records that are not part of the cluster are not coreferent, i.e. when only one record does not belong. 

![screenshot from 2015-04-08 13 08 01](https://cloud.githubusercontent.com/assets/536941/7051807/66a3ae74-ddf0-11e4-8860-a2f4f272cce2.png)

**Comment by evz** [comment]
So, don't learn negative examples unless the whole thing is rejected, right?

**Comment by fgregg** [comment]
Hmm... yes, I suppose that's the other unambiguous setting

So only learn negative examples in two cases

-  only one record does not belong, the combination of that *single* record and all the other records are unambiguously distinct
- **all** records are marked at excluded

**Comment by fgregg** [comment]
Not quite fixed, see https://github.com/datamade/dedupe-api/commit/65b21df#commitcomment-10857802

**Comment by fgregg** [comment]
This code is not correct for the final review step. 

![screenshot from 2015-05-01 13 13 04](https://cloud.githubusercontent.com/assets/536941/7434863/d7d3acb4-f003-11e4-81ea-a782d3f42fe7.png)

For example, int this case. We should add two negative examples (the product of the target records and the last two records). Our current code won't add any.
