### ISSUE TITLE
Canonical Bootstrapping/Deduping 

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#18]
From user point of view

- [x] Upload or connect to data set
- [x] Define data model
- [x] Label training pairs
- [x] Validate clusters
- [x] Review deduplicated clusters #22
  - It's possible that more than one cluster of records refer to the same entity. After reviewing clusters, we create canonicalize records and dedupe them. If the user decides that canonicalized records refer to the same entity, then the clusters are merged
- [x] Match unclustered duplicates #23
  - The clustering phase should be conservative. After we have created the original clustered set, let the user match the remaining, unclustered records, to the entity map. This may be an optional step.

Question: When should we mark a dataset as 'master file' to be added to and augmented by data from other record sets?

**Comment by evz** [comment]
@fgregg Have we figured out an answer to that question yet? It seems like once we have an entry for every record in the original dataset somewhere in the entity map (either as part of a cluster or a single record) that we have a master file, right? Or do we need to go that far?

**Comment by fgregg** [comment]
This is really the question of do we ever want to make an entity map read only, for example if we wanted to treat it as a complete gazetteer. I don't think we need to answer this question now, and we can see if this question re-emerges from actual use.
