### ISSUE TITLE
Reorder steps

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#191]
Working through AJC for the umpteenth time, I realize we should reorganize the review steps.

First should come clustering, and reviewing clustering. As it is now.

Then should we should match the unmatched records to the entity map.

Finally, we should do a merge entities step.

The merging step does not really reduce the amount of work we have to do in matching unmatched records. It does a little by reducing the number of entities a record can be a target of, but in practice it this doesn't seem to make much difference on larger data sets and reviewing the merge entities is almost certainly not worth it.

Let's reorder these.

**Comment by evz** [comment]
working on this over here: https://github.com/datamade/dedupe-api/tree/step_reversal
