### ISSUE TITLE
OPS: Push all messages from sentry to slack

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#213]
I get very confused when messages are recorded by sentry but not sent to slack. Is there any reason not to send everything to slack?

**Comment by evz** [comment]
I think the default is to only send new events. I'll see if I can change it.

**Comment by evz** [comment]
OK, I updated the integrations so that every event that happens should end up in slack.

**Comment by fgregg** [comment]
Thanks, one less reason to feel like I'm being gaslit.
