### ISSUE TITLE
Preprocessing steps?

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#31]
Do we want to include some standard options for preprocessing (removing leading or trailing whitespaces, lowercasing, transliterating to ASCII character set), or should *all* preprocessing happen before it hits the API?

**Comment by fgregg** [comment]
Addressing parsing would be helped if it had original info on casing.

**Comment by evz** [comment]
So, store address components in separate fields?

**Comment by fgregg** [comment]
Components? That comment was more about informing our thinking about when and how to preprocess

**Comment by fgregg** [comment]
Components? That comment was more about informing our thinking about when and how to preprocess

**Comment by fgregg** [comment]
Another example. If the variable type is Price we could check for negative values.

**Comment by evz** [comment]
Currently pre-processing happens when we are attempting to match a new record or when a user redefines the model (or defines it for the first time).
