### ISSUE TITLE
Per Record confidence

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#41]
Let's not show the per-record confidence score. I doubt that it's every going to be that useful to look at. Instead let's sort the records from low confidence (slightly more likely to be an outlier) to high confidence (slightly more likely to be part of the cluster).

**Comment by evz** [comment]
So, sort the records that way within the review queue? Or sort the review queue that way?

**Comment by fgregg** [comment]
So, there's two things. 1. how much confidence we have that an entire cluster is good. 2. how much confidence we have that a record is part of a particular cluster. This issue is about the second bit. When we show the users records, let's sort the records from low confidence to high confidence.
