### ISSUE TITLE
States

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#44]
# 1
```
Data Model Defined | Training Data Exists | Clustering Reviewed | Clusters Deduped 
False              | False                | False               | False 
```
Possible Actions
- Define data model
- Delete project

Notifications
- Whether the data has been fully loaded in. (Should defining data model depend upon fully loading in data?)

Normally the user will add data model and then, immediately, want to add training data.

# 2
```
Data Model Defined | Training Data Exists | Clustering Reviewed | Clusters Deduped 
True               | False                | False               | False 
```
Possible Actions
- Change data model
- Add training data
- Delete project

Notifications
- Whether we are ready to start adding training data. I.e. Have we taken our sample? (Do we want to keep our sample around or take it on demand)?

# 3
```
Data Model Defined | Training Data Exists | Clustering Reviewed | Clusters Deduped 
True               | True                 | False               | False 
```

Possible Actions
- Change data model
- Add training data
- Delete training data (or edit)
- Review cluster
- Delete project

Notification
- Whether clustering has started but not stopped.

If the user changes the data model, she should be given option of either immediately retraining with the existing training data or adding training data.

# 3.5
```
Data Model Defined | Training Data Exists | Clustering Reviewed | Clusters Deduped 
True               | True                 | False               | False 
```

If the datamodel has been updated but reclustering has not been triggered. Then all options as **3** but also

- Train option

# 4
```
Data Model Defined | Training Data Exists | Clustering Reviewed | Clusters Deduped 
True               | True                 | True                | False 
```
Possible actions
- Undo cluster review acceptance (go back to previous stage)
- Dedupe clusters
- Delete project

Notifications
- Whether deduping the clusters is ready ready or still computing

# 5
```
Data Model Defined | Training Data Exists | Clustering Reviewed | Clusters Deduped 
True               | True                 | True                | True 
```
Possible actions
- Delete project
- Go to stage 3 (undo the previous two steps)

Notes:
It should never be possible for a lower state to be False and a later state to be True.

Thoughts, @evz, @derekeder ?

**Comment by evz** [comment]
A form of this is implemented within the framework that I have in place but I need to go through and make sure that it's logic is enforced.

**Comment by evz** [comment]
Once we have the logic here being enforced in a reasonable way, we should make sure that errors are getting returned as appropriate and tests are written to make sure that it is working as expected.

**Comment by derekeder** [comment]
@evz and I have come up with a revised status list, defined here: https://docs.google.com/spreadsheets/d/1b425g9ALqHAh2hrxObjLGWFNRhy1z87HyW_-qrM_0Bc/edit#gid=0

**Comment by fgregg** [comment]
Looking good. 

For step decrement, we may want to decremenent multiple steps. I.e. go from reviewing clusters to refining the model.

**Comment by evz** [comment]
Besides the ``processing`` column, we also added a ``filename`` and ``description`` column to the ``dedupe_session`` table (ya know, for the humans). Handy SQL to get your setup caught up:

```sql
ALTER TABLE dedupe_session ADD COLUMN description TEXT;
ALTER TABLE dedupe_session ADD COLUMN filename VARCHAR;
ALTER TABLE dedupe_session ADD COLUMN processing BOOL;
```

**Comment by evz** [comment]
More alter statements for @derekeder 

```sql
ALTER TABLE dedupe_session ADD COLUMN date_updated TIMESTAMP WITH TIME ZONE;
ALTER TABLE dedupe_session ADD COLUMN date_updated TIMESTAMP WITH TIME ZONE;
ALTER TABLE dedupe_session ADD COLUMN date_added SET DEFAULT CURRENT_TIMESTAMP;
```

**Comment by derekeder** [comment]
I believe this is done.
