### ISSUE TITLE
UI love for matching unmatched records 

### ISSUE THREAD

**Issue by evz** [datamade/dedupe-api#48]
After the initial review, and reviewing the deduplication of canonical clusters, we try to match all of the records that are not represented in the entity map against those that are represented there. I built an interface for this, but it sort of looks like :hankey:

**Comment by derekeder** [comment]
started on this with a1717a1c76e099bd8180b8f7cbc1b0df33453a39

still needs:

* [ ] descriptive text
* [ ] number of records left to match
* [ ] fields sorted in expected order

**Comment by derekeder** [comment]
Handled in #63 #64 #65 #66
