### ISSUE TITLE
Keep better track of various review counts

### ISSUE THREAD

**Issue by evz** [datamade/dedupe-api#51]
Right now the counter on the first review is pretty accurate. However, the counter that is supposed to relate how many clusters are left to review after deduplicating the canonical forms of the clusters found after the first review doesn't do anything and there is no counter relating how many unmatched records there are left to attempt to match to the entity map. Let's fix this.

**Comment by derekeder** [comment]
I believe this is done. All that's left is some display stuff described in #48
