### ISSUE TITLE
Fetch next entity or record based on probability of user acceptance

### ISSUE THREAD

**Issue by derekeder** [datamade/dedupe-api#67]
When we show the user a record, fetch it based on a a calculated score.

This effects the following steps:

* 4. Review entities
* 5. Merge entities
* 6. Final review

**Comment by evz** [comment]
I have this implemented in a somewhat inefficient way for the first two review steps.

**Comment by evz** [comment]
@derekeder Lets talk about how to implement this. I have the number of false positives and false negatives coming back with the response for every new cluster for review. We just need to figure out how to display it.

**Comment by derekeder** [comment]
closed along with #68 via e87ef3c0f143caf5bbee66ce7805912604bc7b9e
