### ISSUE TITLE
Feedback to user on when to 'bulk accept'

### ISSUE THREAD

**Issue by derekeder** [datamade/dedupe-api#68]
Currently, we show a 'bulk accept' button for the review steps. The user should be given information as to the consequences of bulk accepting, including expected number of false positives & false negatives.

We should also hide the accept button below a certain threshold.

Effects the following steps:

* 4. Review entities
* 5. Merge entities
* 6. Final review

**Comment by evz** [comment]
Related to #8

**Comment by derekeder** [comment]
implemented in e87ef3c0f143caf5bbee66ce7805912604bc7b9e

the rest of this work for step 6 is in #88
