### ISSUE TITLE
Got a cluster with a single record to review

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#70]
![screenshot from 2015-01-29 11 18 36](https://cloud.githubusercontent.com/assets/536941/5962304/9a52b310-a7a8-11e4-8b7e-b01a05aa7410.png)

**Comment by evz** [comment]
@fgregg I have not seen this in a while. I am hesitant to close it without really knowing what was causing it in the first place and therefore not really knowing if it's actually fixed.

**Comment by fgregg** [comment]
We'll let's close for now, as "can't reproduce" We can always reopen.

**Comment by evz** [comment]
This has apparently returned.

**Comment by fgregg** [comment]
Entity id: 60bba722-ec78-4fec-a3fa-d14f87aedb0d
Record id: 857822
