### ISSUE TITLE
Merge clustering step seems too conservative

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#71]
Looking at the final output of http://dedupeapi.datamade.us/session-admin/?session_id=cfcc3a09-03bf-4cef-b75e-73ed545e7d4a, JC Decaux appears as a *bunch* of clusters. We should maybe be more liberal with our threshold for the merge clustering?

**Comment by evz** [comment]
@fgregg Now that we can take a dedupe session back to a previous step, does this still seem like something we need to address separately?

**Comment by fgregg** [comment]
I think we can close.
