### ISSUE TITLE
Turning off canopy based predicates for matching (for now)

### ISSUE THREAD

**Issue by evz** [datamade/dedupe-api#76]
Until we can get around #75 and #74, we'll disable canopy based predicates when matching unmatched records to a canonical dataset.

**Comment by evz** [comment]
This is implemented in the function that gets the dedupe session ready for matching unmatched records against it [like so](https://github.com/datamade/dedupe-api/blob/38f7bb3cbbce67e0f4cb14a9fe02ce09c2015845/api/utils/delayed_tasks.py#L159-L162)

**Comment by fgregg** [comment]
Nice! Look forward to seeing how this affects matching behavior.
