### ISSUE TITLE
Permissons for entity map are set to read only

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#77]
When I download the entity map for a session, the permissions are always set to read only. Which is annoying.

**Comment by evz** [comment]
This might be an OS / browser thing. That file is created on the fly when you click the button and is never written to any file system until it gets written to yours. When I download that file, the permissions look like this:

![screen shot 2015-02-02 at 10 19 01 am](https://cloud.githubusercontent.com/assets/551491/6003924/00169b7a-aac5-11e4-87e4-8e332be9c907.png)

**Comment by fgregg** [comment]
Okay.
