### ISSUE TITLE
Use cluster reviews to learn a better confidence for clusters

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#8]
logit(Review = Yes) = cluster_score + len(cluster) + cluster_score * len(cluster)

After 30 or so reviews, we could then set a high precision threshold for the remaining clusters in the queue. 

Where would somethign like this belong? 

The API?
Some middleware that either makes automated decisions or passes records on to clerical review?

**Comment by fgregg** [comment]
@evz will you think about the right place for this and we can work on it together next Wednesday?

**Comment by evz** [comment]
I've added the basic components for accomplishing this here 550efcfc0116ff3c5456177210682672ab3d06de Still need some performance optimization.

**Comment by evz** [comment]
What we have going now seems to be working pretty well, even on larger datasets
