### ISSUE TITLE
Only figure out exact duplicates one time.

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#83]
RIght now, if we resample data we recompute the exact duplicates. This can take a long time, only do this once.

**Comment by evz** [comment]
Thinking about this a bit more, the way that I calculate the exact duplicates is to group by the fields that the user has selected when defining the model. This could change if a user redefines the model which would necessitate recomputing exact duplicates. With that in mind, I'll only recompute it when it's needed.
