### ISSUE TITLE
File upload not handling quoted strings with commas accurately

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#85]
![screenshot from 2015-02-05 10 48 42](https://cloud.githubusercontent.com/assets/536941/6064601/978d1c48-ad24-11e4-93e6-049f4961bfbe.png)

Notice that names not correctly split.

Source data is here: https://github.com/cjdd3b/fec-standardizer/tree/master/data

**Comment by evz** [comment]
Fixed by using a csv reader instead of doing this the dumb way.
