### ISSUE TITLE
update entity map with failed matches between steps 5 and 6

### ISSUE THREAD

**Issue by derekeder** [datamade/dedupe-api#88]
Before showing the user records that are not part of a cluster in step 6, batch run the match process and update the entity map with records that fail to match. This will leave the final step with only the records that have a potential match.

Related to #68

**Comment by evz** [comment]
I'm working on this in the bulk-match branch. The approach is a bit more nuanced (we're doing all of the churning on the server which should make it quite a lot faster).

**Comment by evz** [comment]
Closed with merge of bulk-match branch
