### ISSUE TITLE
Make a thing to update settings files

### ISSUE THREAD

**Issue by evz** [datamade/dedupe-api#94]
The core Dedupe library changes. When it does we often need to update the settings files for sessions that are in progress in order to be able to stay current with the current state of the art. Is there a better way to do this besides just re-running the training and saving out the settings files again @fgregg ?

**Comment by fgregg** [comment]
No. that's the best way I've been able to think of.

**Comment by fgregg** [comment]
We should have a function that just retrains what we need to retrain.

**Comment by fgregg** [comment]
#139 depends on this right?
