### ISSUE TITLE
When reviewing, sort the columns left-right by importance

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#96]
Put the field that we've learned is most discriminative first, etc.

**Comment by evz** [comment]
How do we know what is most discriminative? Is that the "Learned Weight"?

**Comment by fgregg** [comment]
We don't really have a complete solution, but let's start with this.

- Any fields that were learned as part of a blocking predicate goes first
- After that (or within that) 'Name' fields get first priority, 'Address
Fields' get second priority

make sense?
